name: Step Outputs
on: workflow_dispatch
jobs:
  jobOne:
    name: First Job to try out step outputs
    runs-on: ubuntu-latest
    steps:
      - name: Set branch output to variable
        id: branch-name
        run: echo 'stage={GITHUB_REF#/ref/*/}' >> GITHUB_OUTPUT';'

      - name: Access outputs
        run: echo "${{steps.branch-name.outputs.stage}}"