name: Step Outputs
on: 
  - workflow_dispatch
  - push
jobs:
  jobOne:
    name: First Job to try out step outputs
    runs-on: ubuntu-latest
    steps:
      - name: Set branch output to variable
        id: branch-name
        run: echo 'stage=${GITHUB_REF#refs/*/}' >> $GITHUB_OUTPUT

      - name: Access outputs - new syntax
        run: echo "${{steps.branch-name.outputs.stage}}"

      - name: Set branch name
        id: vars
        run: echo ::set-output name=stage::${GITHUB_REF#refs/*/}

      - name: Access outputs - old syntax
      run: echo "${{steps.vars.outputs.stage}}"